import type { ElementConfig } from './types';

export const ELEMENTS: ElementConfig[] = [
  {
    id: 'roof',
    label: 'Dak',
    icon: '🏠',
    colors: [
      { id: 'anthracite',   label: 'Antraciet',       hex: '#2d2d2d', promptName: 'anthracite grey' },
      { id: 'matte-black',  label: 'Mat zwart',        hex: '#111111', promptName: 'matte black' },
      { id: 'charcoal',     label: 'Houtskool',        hex: '#383838', promptName: 'charcoal grey' },
      { id: 'slate-blue',   label: 'Leisteen blauw',   hex: '#4a5568', promptName: 'slate blue-grey' },
      { id: 'terracotta',   label: 'Terracotta',       hex: '#c1440e', promptName: 'terracotta clay red' },
      { id: 'classic-red',  label: 'Klassiek rood',    hex: '#9b2c1a', promptName: 'classic dark red' },
      { id: 'dark-brown',   label: 'Donker bruin',     hex: '#3d2b1f', promptName: 'dark chocolate brown' },
      { id: 'warm-brown',   label: 'Warm bruin',       hex: '#6b4226', promptName: 'warm timber brown' },
      { id: 'moss-green',   label: 'Mosgroen',         hex: '#4a5240', promptName: 'moss green' },
      { id: 'patina-green', label: 'Patina groen',     hex: '#3d6b5a', promptName: 'oxidized copper patina green' },
      { id: 'sand',         label: 'Zandkleur',        hex: '#c8b48a', promptName: 'sandy beige' },
      { id: 'white-med',    label: 'Mediterraans wit', hex: '#e8e4d8', promptName: 'mediterranean white' },
      { id: 'graphite',     label: 'Grafiet',          hex: '#1e1e1e', promptName: 'graphite black' },
      { id: 'steel-grey',   label: 'Staalgrijs',       hex: '#708090', promptName: 'steel grey' },
      { id: 'deep-navy',    label: 'Donker navy',      hex: '#1a2744', promptName: 'deep navy blue' },
    ],
  },
  {
    id: 'facade',
    label: 'Gevel',
    icon: '🧱',
    colors: [
      { id: 'pure-white',   label: 'Zuiver wit',       hex: '#f8f8f5', promptName: 'pure white' },
      { id: 'warm-white',   label: 'Warm wit',         hex: '#f2ece0', promptName: 'warm white' },
      { id: 'cream',        label: 'Crème',            hex: '#f0e8d0', promptName: 'warm cream' },
      { id: 'ivory',        label: 'Ivoor',            hex: '#ede8d0', promptName: 'ivory white' },
      { id: 'light-grey',   label: 'Lichtgrijs',       hex: '#d4d4d4', promptName: 'light grey' },
      { id: 'mid-grey',     label: 'Middengrijs',      hex: '#a0a0a0', promptName: 'medium grey' },
      { id: 'charcoal',     label: 'Antraciet',        hex: '#3a3a3a', promptName: 'dark charcoal' },
      { id: 'near-black',   label: 'Bijna zwart',      hex: '#1e1e1e', promptName: 'near black' },
      { id: 'sand',         label: 'Zand',             hex: '#c8b89a', promptName: 'sandy beige' },
      { id: 'taupe',        label: 'Taupe',            hex: '#b0a090', promptName: 'warm taupe' },
      { id: 'sage',         label: 'Salie groen',      hex: '#8fa88a', promptName: 'sage green' },
      { id: 'olive',        label: 'Olijfgroen',       hex: '#6b7a50', promptName: 'olive green' },
      { id: 'forest',       label: 'Bosgroen',         hex: '#2d4a35', promptName: 'deep forest green' },
      { id: 'brick-red',    label: 'Baksteenrood',     hex: '#9e4a2d', promptName: 'brick red' },
      { id: 'terracotta',   label: 'Terracotta',       hex: '#c26b45', promptName: 'terracotta' },
      { id: 'ocher',        label: 'Oker geel',        hex: '#c8922a', promptName: 'golden ochre' },
      { id: 'blush',        label: 'Roze blush',       hex: '#d4a8a0', promptName: 'blush pink' },
      { id: 'navy',         label: 'Marineblauw',      hex: '#1e2d4a', promptName: 'navy blue' },
      { id: 'steel-blue',   label: 'Staalblauw',       hex: '#4a6080', promptName: 'steel blue' },
      { id: 'concrete',     label: 'Beton',            hex: '#808080', promptName: 'raw concrete grey' },
    ],
  },
  {
    id: 'windows',
    label: 'Ramen',
    icon: '🪟',
    colors: [
      { id: 'anthracite',   label: 'Antraciet',        hex: '#3d3d3d', promptName: 'anthracite grey window frames' },
      { id: 'matte-black',  label: 'Mat zwart',        hex: '#1a1a1a', promptName: 'matte black window frames' },
      { id: 'graphite',     label: 'Grafiet',          hex: '#2d2d2d', promptName: 'graphite window frames' },
      { id: 'white',        label: 'Wit',              hex: '#f0f0f0', promptName: 'bright white window frames' },
      { id: 'cream-white',  label: 'Crème wit',        hex: '#ede8e0', promptName: 'cream white window frames' },
      { id: 'warm-brown',   label: 'Warm bruin',       hex: '#6b4c2a', promptName: 'warm brown timber frames' },
      { id: 'dark-oak',     label: 'Donker eiken',     hex: '#4a3020', promptName: 'dark oak wood frames' },
      { id: 'bronze',       label: 'Brons',            hex: '#7d5a3c', promptName: 'bronze metal frames' },
      { id: 'champagne',    label: 'Champagne',        hex: '#c8b480', promptName: 'champagne aluminium frames' },
      { id: 'steel-grey',   label: 'Staalgrijs',       hex: '#607080', promptName: 'steel grey aluminium frames' },
      { id: 'navy',         label: 'Marineblauw',      hex: '#1e2d4a', promptName: 'navy blue window frames' },
      { id: 'forest-green', label: 'Bosgroen',         hex: '#2d4a35', promptName: 'forest green window frames' },
    ],
  },
  {
    id: 'door',
    label: 'Voordeur',
    icon: '🚪',
    colors: [
      { id: 'matte-black',  label: 'Mat zwart',        hex: '#1a1a1a', promptName: 'matte black front door' },
      { id: 'anthracite',   label: 'Antraciet',        hex: '#3d3d3d', promptName: 'anthracite grey front door' },
      { id: 'graphite',     label: 'Grafiet',          hex: '#2a2a2a', promptName: 'graphite front door' },
      { id: 'white',        label: 'Wit',              hex: '#f0f0f0', promptName: 'bright white front door' },
      { id: 'cream',        label: 'Crème',            hex: '#ede8d8', promptName: 'cream white front door' },
      { id: 'natural-oak',  label: 'Naturel eiken',    hex: '#c8a050', promptName: 'natural light oak wood door' },
      { id: 'dark-oak',     label: 'Donker eiken',     hex: '#6b4820', promptName: 'dark oak wood door' },
      { id: 'walnut',       label: 'Walnoot',          hex: '#4a2c0a', promptName: 'dark walnut wood door' },
      { id: 'teak',         label: 'Teak',             hex: '#8b5e2a', promptName: 'teak wood door' },
      { id: 'deep-red',     label: 'Diep rood',        hex: '#8b1a1a', promptName: 'deep burgundy red door' },
      { id: 'tomato-red',   label: 'Tomaatrood',       hex: '#c0392b', promptName: 'vibrant tomato red door' },
      { id: 'navy',         label: 'Marineblauw',      hex: '#1a2a4a', promptName: 'navy blue front door' },
      { id: 'cobalt',       label: 'Kobaltblauw',      hex: '#1a3a8a', promptName: 'cobalt blue front door' },
      { id: 'forest-green', label: 'Bosgroen',         hex: '#1a3a2a', promptName: 'dark forest green door' },
      { id: 'sage-green',   label: 'Saliegroen',       hex: '#6b8a6a', promptName: 'sage green door' },
      { id: 'mustard',      label: 'Mosterd geel',     hex: '#c8922a', promptName: 'mustard yellow door' },
      { id: 'terracotta',   label: 'Terracotta',       hex: '#c26b45', promptName: 'terracotta door' },
      { id: 'bordeaux',     label: 'Bordeaux',         hex: '#5c1a2a', promptName: 'bordeaux wine red door' },
    ],
  },
];

export const DEFAULT_CONFIG = {
  roof: 'anthracite',
  facade: 'pure-white',
  windows: 'anthracite',
  door: 'matte-black',
  facadeMaterial: 'plaster',
  roofMaterial: 'tiles',
};

export function getColorOption(elementId: keyof typeof DEFAULT_CONFIG, colorId: string) {
  const element = ELEMENTS.find((e) => e.id === elementId);
  return element?.colors.find((c) => c.id === colorId);
}

export const POPULAR_COMBOS = [
  { label: 'Modern Zwart',  config: { roof: 'matte-black',  facade: 'pure-white',  windows: 'matte-black',  door: 'matte-black',  facadeMaterial: 'plaster',   roofMaterial: 'metal' } },
  { label: 'Scandinavisch', config: { roof: 'anthracite',   facade: 'warm-white',  windows: 'anthracite',   door: 'natural-oak',  facadeMaterial: 'wood',      roofMaterial: 'tiles' } },
  { label: 'Klassiek Bruin',config: { roof: 'terracotta',   facade: 'cream',       windows: 'warm-brown',   door: 'dark-oak',     facadeMaterial: 'brick',     roofMaterial: 'tiles' } },
  { label: 'Industrial',    config: { roof: 'graphite',     facade: 'concrete',    windows: 'matte-black',  door: 'anthracite',   facadeMaterial: 'concrete',  roofMaterial: 'metal' } },
  { label: 'Warm Landelijk',config: { roof: 'dark-brown',   facade: 'sand',        windows: 'warm-brown',   door: 'walnut',       facadeMaterial: 'brick',     roofMaterial: 'tiles' } },
  { label: 'Coastal Blauw', config: { roof: 'slate-blue',   facade: 'pure-white',  windows: 'navy',         door: 'navy',         facadeMaterial: 'plaster',   roofMaterial: 'slate' } },
  { label: 'Mediterraan',   config: { roof: 'terracotta',   facade: 'warm-white',  windows: 'white',        door: 'natural-oak',  facadeMaterial: 'plaster',   roofMaterial: 'tiles' } },
  { label: 'Groen Modern',  config: { roof: 'matte-black',  facade: 'forest',      windows: 'matte-black',  door: 'natural-oak',  facadeMaterial: 'composite', roofMaterial: 'metal' } },
];
